# SO-101 Simulation Parameters
# Domain randomization and simulation configuration

simulation:
  # Gazebo simulation settings
  gazebo:
    physics_engine: "ode"
    max_step_size: 0.001
    real_time_factor: 1.0
    real_time_update_rate: 1000
    max_contacts: 20
    
  # Robot configuration
  robot:
    model: "so101_dual_arm"
    arms:
      left:
        controller: "left_arm_controller"
        gripper: "left_gripper_controller"
        joint_names:
          - "left_shoulder_pitch"
          - "left_shoulder_roll"
          - "left_shoulder_yaw"
          - "left_elbow_pitch"
          - "left_elbow_roll"
          - "left_wrist_pitch"
          - "left_wrist_roll"
          - "left_wrist_yaw"
      right:
        controller: "right_arm_controller"
        gripper: "right_gripper_controller"
        joint_names:
          - "right_shoulder_pitch"
          - "right_shoulder_roll"
          - "right_shoulder_yaw"
          - "right_elbow_pitch"
          - "right_elbow_roll"
          - "right_wrist_pitch"
          - "right_wrist_roll"
          - "right_wrist_yaw"

# Domain randomization parameters
domain_randomization:
  enabled: true
  
  # Lighting randomization
  lighting:
    ambient_light:
      min: [0.3, 0.3, 0.3]
      max: [0.8, 0.8, 0.8]
    directional_light:
      min: [0.5, 0.5, 0.5]
      max: [1.0, 1.0, 1.0]
    shadow_quality: [1, 2, 3]  # Low, Medium, High
    
  # Material randomization
  materials:
    friction:
      min: 0.1
      max: 0.8
    restitution:
      min: 0.0
      max: 0.5
    mass:
      min: 0.1
      max: 2.0
      
  # Camera randomization
  cameras:
    noise:
      mean: 0.0
      std: [0.01, 0.05]
    blur:
      kernel_size: [1, 3, 5]
    exposure:
      min: 0.5
      max: 2.0
      
  # Object randomization
  objects:
    position_noise:
      std: [0.01, 0.02, 0.01]  # x, y, z
    orientation_noise:
      std: [0.05, 0.05, 0.05]  # roll, pitch, yaw
    scale:
      min: 0.8
      max: 1.2

# Episode generation settings
episode_generation:
  max_episode_length: 300  # seconds
  num_episodes: 1000
  success_threshold: 0.95
  
  # Task randomization
  tasks:
    - "pick_and_place"
    - "stack_objects"
    - "insert_peg"
    - "open_drawer"
    - "pour_liquid"
    
  # Object types for randomization
  objects:
    - "cube"
    - "sphere"
    - "cylinder"
    - "box"
    - "bottle"
    - "plate"
    - "bowl"
    - "cup"
    
  # Environment randomization
  environments:
    - "table_scene"
    - "kitchen_scene"
    - "workshop_scene"
    - "office_scene"
    - "laboratory_scene"

# Data collection settings
data_collection:
  topics:
    - "/joint_states"
    - "/tf"
    - "/tf_static"
    - "/camera/left/image_raw"
    - "/camera/right/image_raw"
    - "/camera/left/depth/image_raw"
    - "/camera/right/depth/image_raw"
    - "/vr/left_hand"
    - "/vr/right_hand"
    - "/vr/left_gripper"
    - "/vr/right_gripper"
    - "/arm_commands"
    - "/gripper_commands"
    
  recording:
    format: "bag"
    compression: "lz4"
    max_size: "10GB"
    
  # LeRobot dataset format
  lerobot_format:
    enabled: true
    output_dir: "~/data/datasets/sim_train"
    metadata:
      robot_type: "so101_dual_arm"
      task_type: "manipulation"
      data_source: "simulation"

# Performance settings
performance:
  # GPU acceleration
  gpu:
    enabled: true
    device: "auto"  # or specific device like "cuda:0"
    
  # Multi-threading
  threading:
    num_workers: 4
    use_multiprocessing: true
    
  # Memory management
  memory:
    max_memory_usage: "8GB"
    garbage_collection: true 