robot_config:
  type: "franka"
  model: "panda"
  dof: 7
  has_gripper: true
  control_interface: "franka_hw"
  joint_limits:
    - [-2.8973, 2.8973]
    - [-1.7628, 1.7628]
    - [-2.8973, 2.8973]
    - [-3.0718, -0.0698]
    - [-2.8973, 2.8973]
    - [-0.0175, 3.7525]
    - [-2.8973, 2.8973] 